### ISSUE TITLE
Cannot delete pods

### ISSUE THREAD

**Issue by gtirloni** [kubernetes-incubator/cri-o#595]
CentOS 7.3
Kubernetes 1.6.4
runc 1.0.0-6.gite800860.el7
cri-o (83b33e826720bbf61929fed7e1a998cb728ba08f)

All installation works and `kubeadm init` finishes. Deploying the Calico network fails.

To clean things up, I deleted Calico's deployment but the pods could not be deleted.

Trying to delete them manually has no impact, same errors. Pods go into "Terminating" status and back to "Running" and "CrashLoopBackOff".

```
Jun 13 15:43:32 master kubelet: I0613 15:43:32.242582    2064 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/1dbd5307-504e-11e7-828b-020000000346-calico-cni-plugin-token-fbq8k" (spec.Name: "calico-cni-plugin-token-fbq8k") pod "1dbd5307-504e-11e7-828b-020000000346" (UID: "1dbd5307-504e-11e7-828b-020000000346").
Jun 13 15:43:32 master kubelet: I0613 15:43:32.521555    2064 kuberuntime_manager.go:458] Container {Name:calico-node Image:quay.io/calico/node:v1.3.0 Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:ETCD_ENDPOINTS Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:etcd_endpoints,Optional:nil,},SecretKeyRef:nil,}} {Name:CALICO_NETWORKING_BACKEND Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:calico_backend,Optional:nil,},SecretKeyRef:nil,}} {Name:CALICO_DISABLE_FILE_LOGGING Value:true ValueFrom:nil} {Name:FELIX_DEFAULTENDPOINTTOHOSTACTION Value:ACCEPT ValueFrom:nil} {Name:CALICO_IPV4POOL_CIDR Value:192.168.0.0/16 ValueFrom:nil} {Name:CALICO_IPV4POOL_IPIP Value:always ValueFrom:nil} {Name:FELIX_IPV6SUPPORT Value:false ValueFrom:nil} {Name:FELIX_LOGSEVERITYSCREEN Value:info ValueFrom:nil} {Name:IP Value: ValueFrom:nil}] Resources:{Limits:map[] Requests:map[cpu:{i:{value:250 scale:-3} d:{Dec:<nil>} s:250m Format:DecimalSI}]} VolumeMounts:[{Name:lib-modules ReadOnly:true MountPath:/lib/modules SubPath:} {Name:var-run-calico ReadOnly:false MountPath:/var/run/calico SubPath:} {Name:calico-cni-plugin-token-fbq8k ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Jun 13 15:43:32 master kubelet: I0613 15:43:32.521647    2064 kuberuntime_manager.go:458] Container {Name:install-cni Image:quay.io/calico/cni:v1.9.1 Command:[/install-cni.sh] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:ETCD_ENDPOINTS Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:etcd_endpoints,Optional:nil,},SecretKeyRef:nil,}} {Name:CNI_NETWORK_CONFIG Value: ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:cni_network_config,Optional:nil,},SecretKeyRef:nil,}}] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:cni-bin-dir ReadOnly:false MountPath:/host/opt/cni/bin SubPath:} {Name:cni-net-dir ReadOnly:false MountPath:/host/etc/cni/net.d SubPath:} {Name:calico-cni-plugin-token-fbq8k ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Jun 13 15:43:32 master crio: time="2017-06-13 15:43:32.532282159Z" level=warning msg="requested logPath for ctr id d7325cf2019b95364c96aea784bfe96e440fa7fa2086e86f568300e8d57dbd42 is a relative path: install-cni_0.log"
Jun 13 15:43:32 master conmon: conmon <ninfo>: about to waitpid: 24175
Jun 13 15:43:32 master crio: [conmon:i]: about to waitpid: 24175
Jun 13 15:43:32 master crio: time="2017-06-13 15:43:32.919716790Z" level=info msg="Running conmon under slice kubepods.slice-kubepods_burstable.slice-kubepods_burstable_pod1dbd5307_504e_11e7_828b_020000000346.slice.slice and unitName crio-kube-system-calico-node-f15vz-1-install-cni-0.scope"
Jun 13 15:43:32 master systemd: Started crio-kube-system-calico-node-f15vz-1-install-cni-0.scope.
Jun 13 15:43:32 master systemd: Starting crio-kube-system-calico-node-f15vz-1-install-cni-0.scope.
Jun 13 15:43:32 master systemd: Scope libcontainer-24175-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Jun 13 15:43:32 master systemd: Scope libcontainer-24175-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Jun 13 15:43:32 master systemd: Created slice libcontainer_24175_systemd_test_default.slice.
Jun 13 15:43:32 master systemd: Starting libcontainer_24175_systemd_test_default.slice.
Jun 13 15:43:32 master systemd: Removed slice libcontainer_24175_systemd_test_default.slice.
Jun 13 15:43:32 master systemd: Stopping libcontainer_24175_systemd_test_default.slice.
Jun 13 15:43:32 master systemd: Started libcontainer container d7325cf2019b95364c96aea784bfe96e440fa7fa2086e86f568300e8d57dbd42.
Jun 13 15:43:32 master dockerd-current: time="2017-06-13T15:43:32.974758986Z" level=error msg="Handler for GET /containers/d7325cf2019b95364c96aea784bfe96e440fa7fa2086e86f568300e8d57dbd42/json returned error: No such container: d7325cf2019b95364c96aea784bfe96e440fa7fa2086e86f568300e8d57dbd42"
Jun 13 15:43:32 master systemd: Starting libcontainer container d7325cf2019b95364c96aea784bfe96e440fa7fa2086e86f568300e8d57dbd42.
Jun 13 15:43:32 master kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 13 15:43:33 master conmon: conmon <error>: Failed to create container: exit status 1
Jun 13 15:43:33 master crio: [conmon:e]: Failed to create container: exit status 1
Jun 13 15:43:33 master crio: time="2017-06-13 15:43:32.999284360Z" level=info msg="Received container pid: -1"
Jun 13 15:43:33 master kubelet: E0613 15:43:33.116258    2064 remote_runtime.go:181] CreateContainer in sandbox "d2b3066fa9fecb4cb4a1274e9ff6374f70c2fd1267a4ef62cfa73d089acf890f" from runtime service failed: rpc error: code = 2 desc = container create failed: container_linux.go:259: starting container process caused "chdir to cwd (\"/opt/cni/bin\") set in config.json failed: no such file or directory"
Jun 13 15:43:33 master kubelet: E0613 15:43:33.116361    2064 kuberuntime_manager.go:719] container start failed: rpc error: code = 2 desc = container create failed: container_linux.go:259: starting container process caused "chdir to cwd (\"/opt/cni/bin\") set in config.json failed: no such file or directory"
Jun 13 15:43:33 master kubelet: : Create Container Failed
Jun 13 15:43:33 master kubelet: I0613 15:43:33.116380    2064 kuberuntime_manager.go:742] checking backoff for container "calico-node" in pod "calico-node-f15vz_kube-system(1dbd5307-504e-11e7-828b-020000000346)"
Jun 13 15:43:33 master kubelet: I0613 15:43:33.116524    2064 kuberuntime_manager.go:752] Back-off 40s restarting failed container=calico-node pod=calico-node-f15vz_kube-system(1dbd5307-504e-11e7-828b-020000000346)
Jun 13 15:43:33 master kubelet: E0613 15:43:33.116562    2064 pod_workers.go:182] Error syncing pod 1dbd5307-504e-11e7-828b-020000000346 ("calico-node-f15vz_kube-system(1dbd5307-504e-11e7-828b-020000000346)"), skipping: [failed to "StartContainer" for "install-cni" with rpc error: code = 2 desc = container create failed: container_linux.go:259: starting container process caused "chdir to cwd (\"/opt/cni/bin\") set in config.json failed: no such file or directory"
Jun 13 15:43:33 master kubelet: : "Create Container Failed"
Jun 13 15:43:33 master kubelet: , failed to "StartContainer" for "calico-node" with CrashLoopBackOff: "Back-off 40s restarting failed container=calico-node pod=calico-node-f15vz_kube-system(1dbd5307-504e-11e7-828b-020000000346)"
Jun 13 15:43:33 master kubelet: ]
```

**Comment by gtirloni** [comment]
```
# crioctl pod stop --id d2b3066fa9fecb4cb4a1274e9ff6374f70c2fd1267a4ef62cfa73d089acf890f
stopping the pod sandbox failed: rpc error: code = 2 desc = failed to destroy network for container kube-system-calico-node-f15vz-1-infra in sandbox d2b3066fa9fecb4cb4a1274e9ff6374f70c2fd1267a4ef62cfa73d089acf890f: cni config uninitialized
```

**Comment by runcom** [comment]
@gtirloni I guess you need to `kubectl delete deploy` for calico otherwise kube restarts it? @sameo ptal if you can

**Comment by runcom** [comment]
@sameo also I think we shouldn't fail on pod stop if net is  uninitialized right?

**Comment by gtirloni** [comment]
@runcom I have already deleted the deployment and Kubernetes keeps trying to delete the underlying pods but fails over and over.

```
# kubectl -n kube-system get deploy
NAME       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-dns   1         1         1            0           40m

# kubectl -n kube-system get pod
NAME                                                     READY     STATUS              RESTARTS   AGE
calico-etcd-c0xjv                                        1/1       Running             0          18m
calico-node-b1p1d                                        0/2       CrashLoopBackOff    8          18m
etcd-master                      1/1       Running             1          40m
kube-apiserver-master            1/1       Running             1          40m
kube-controller-manager-master   1/1       Running             1          40m
kube-dns-3913472980-hpk9k                                0/3       ContainerCreating   0          41m
kube-proxy-66gl5                                         1/1       Running             1          41m
kube-scheduler-master            1/1       Running             1          40m

# kubectl -n kube-system delete pod calico-etcd-c0xjv calico-node-b1p1d
pod "calico-etcd-c0xjv" deleted
pod "calico-node-b1p1d" deleted

# kubectl -n kube-system get pod
NAME                                                     READY     STATUS              RESTARTS   AGE
calico-etcd-c0xjv                                        1/1       Terminating         0          18m
calico-node-b1p1d                                        0/2       Terminating         8          18m
etcd-master                      1/1       Running             1          40m
kube-apiserver-master            1/1       Running             1          40m
kube-controller-manager-master   1/1       Running             1          40m
kube-dns-3913472980-hpk9k                                0/3       ContainerCreating   0          41m
kube-proxy-66gl5                                         1/1       Running             1          41m
kube-scheduler-master            1/1       Running             1          40m
```

The go from Terminating to ContainerCreating again.

```
# kubectl get all -n kube-system
NAME                                                        READY     STATUS              RESTARTS   AGE
po/calico-etcd-mm885                                        1/1       Running             0          28s
po/calico-node-77bpd                                        0/2       CrashLoopBackOff    2          40s
po/etcd-master                      1/1       Running             1          41m
po/kube-apiserver-master            1/1       Running             1          41m
po/kube-controller-manager-master   1/1       Running             1          41m
po/kube-dns-3913472980-hpk9k                                0/3       ContainerCreating   0          42m
po/kube-proxy-66gl5                                         1/1       Running             1          42m
po/kube-scheduler-master            1/1       Running             1          41m

NAME              CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
svc/calico-etcd   10.96.232.136   <none>        6666/TCP        41m
svc/kube-dns      10.96.0.10      <none>        53/UDP,53/TCP   42m

NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/kube-dns   1         1         1            0           42m

NAME                     DESIRED   CURRENT   READY     AGE
rs/kube-dns-3913472980   1         1         0         42m

# kubectl get deploy  --all-namespaces
NAMESPACE     NAME       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   kube-dns   1         1         1            0           44m
```

**Comment by sameo** [comment]
@gtirloni Can you try applying this patch:

```Go
diff --git a/server/sandbox_stop.go b/server/sandbox_stop.go
index fb998b1..a842312 100644
--- a/server/sandbox_stop.go
+++ b/server/sandbox_stop.go
@@ -36,8 +36,10 @@ func (s *Server) StopPodSandbox(ctx context.Context, req *pb.StopPodSandboxReque
        }
        if _, err := os.Stat(netnsPath); err == nil {
                if err2 := s.netPlugin.TearDownPod(netnsPath, sb.namespace, sb.kubeName, sb.id); err2 != nil {
-                       return nil, fmt.Errorf("failed to destroy network for container %s in sandbox %s: %v",
+                       logrus.Warnf("failed to destroy network for container %s in sandbox %s: %v",
                                podInfraContainer.Name(), sb.id, err2)
+//                     return nil, fmt.Errorf("failed to destroy network for container %s in sandbox %s: %v",
+//                             podInfraContainer.Name(), sb.id, err2)
                }
        } else if !os.IsNotExist(err) { // it's ok for netnsPath to *not* exist
                return nil, fmt.Errorf("failed to stat netns path for container %s in sandbox %s before tearing down the network: %v",
```

It should fix the pod destroying part. However, it seems calico is not installing a CNI configuration so there's something else going on:

```
calico-node-b1p1d                                        0/2       CrashLoopBackOff    8
```

Can you get the logs for this specific pod ?

**Comment by gtirloni** [comment]
@sameo thanks for taking a look at this.

I applied your patch and it looks like the error is now a warning, as I think you intended.

The pods still fail to get created and I got a bit list with so many messages. I pasted it all here hoping it's more useful than trying to fish individual pieces: https://pastebin.com/raw/aq8NwnRX

Here's the logs from Calico:

```
# kubectl -n kube-system logs -c calico-node calico-node-gbm7s
time="2017-06-13T16:37:54Z" level=info msg="NODENAME environment not specified - check HOSTNAME" 
******************************************************************************
* WARNING                                                                    *
* Auto-detecting node name.  It is recommended that an explicit fixed value  *
* is supplied using the NODENAME environment variable.  Using a fixed value  *
* ensures that any changes to the compute host's hostname will not affect    *
* the Calico configuration when calico/node restarts.                        *
******************************************************************************
time="2017-06-13T16:37:54Z" level=info msg="Loading config from environment" 
Skipping datastore connection test
Using autodetected IPv4 address on interface eth0: 200.200.200.0/24
No AS number configured on node resource, using global value
time="2017-06-13T16:37:54Z" level=info msg="Building new node resource" Name=mrsdalloway 
time="2017-06-13T16:37:54Z" level=info msg="Initialise BGP data" 
Calico node 'master' is already using the IPv4 address 200.200.200.70:
 -  Check the node configuration to remove the IP address conflict
Terminating
Calico node failed to start

# kubectl -n kube-system logs -c install-cni calico-node-gbm7s
Error from server (BadRequest): container "install-cni" in pod "calico-node-gbm7s" is waiting to start: rpc error: code = 2 desc = container create failed: container_linux.go:259: starting container process caused "chdir to cwd (\"/opt/cni/bin\") set in config.json failed: no such file or directory"
```

However, I don't know if this is related to cri-o or not. I wanted to clean everything up and start from scratch. Not sure how trustworthy these logs are now.

**Comment by runcom** [comment]
@sameo are you making a pr with the patch above? :)

**Comment by sameo** [comment]
@runcom Yes, I will do so tomorrow :) Then I'll test calico on my side.

**Comment by sameo** [comment]
@gtirloni I assume you used http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml for your calico pods ?

**Comment by gtirloni** [comment]
@same that's right, v2.3 of that doc.

**Comment by runcom** [comment]
will be fixed by #599 and #598

**Comment by gtirloni** [comment]
@runcom @sameo thank you a lot!

**Comment by adiri** [comment]
I'm having the same problem with Calico 2.4. k8s 1.7.3 using kubeadm to install it.

I install a node then delete the node and on the same IP address install a different node with a different name...

```
Calico node 'worker804945757' is already using the IPv4 address 10.0.0.5:
 -  Check the node configuration to remove the IP address conflict
Terminating
Calico node failed to start
```

worker804945757 is already deleted. how do I clean Calicos pool or this specific entry?

**Comment by freewilll** [comment]
Same here. Calico v2.6. k8s 1.7.5 using kubeadm.

Steps taken:
```
kubeadm reset
kubeadm init --apiserver-advertise-address 10.0.1.1 --pod-network-cidr=192.168.0.0/16
kubectl apply -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml

# Then on another node
kubeadm join ...
```

Resulting in
```
Skipping datastore connection test
Using autodetected IPv4 address on interface br-abbf62fcab8b: 172.18.0.1/16
Calico node 'master' is already using the IPv4 address 172.18.0.1:
 -  Check the node configuration to remove the IP address conflict
Terminating
Calico node failed to start
```
