### ISSUE TITLE
Missing libostree-1-1 for Ubuntu Xenial

### ISSUE THREAD

**Issue by sameo** [kubernetes-incubator/cri-o#817]
When trying to install CRI-O from the Ubuntu [Atomic PPA](https://launchpad.net/~projectatomic/+archive/ubuntu/ppa), I get the following error:

```
# apt-get install cri-o
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cri-o : Depends: libostree-1-1 but it is not installable
```

I'm on Xenial:

```
# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

As a matter of fact, there seems to be no libostree-1-1 package for xenial:
https://packages.ubuntu.com/search?keywords=libostree-1-1

**Comment by sameo** [comment]
cc @lsm5 @runcom

**Comment by runcom** [comment]
We should just remove ostree from building, there's a go build tag to remove it we should use when building for ubuntu.

**Comment by lsm5** [comment]
On Wed, Aug 30, 2017 at 12:28:04PM +0000, Antonio Murdaca wrote:
> We should just remove ostree from building, there's a go build tag to remove it we should use when building for ubuntu. 

I'll check it out.

@sameo until I get a new build out, please try this:

    add-apt-repository ppa:alexlarsson/flatpak
    apt update
    apt install libostree-1-1


> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes-incubator/cri-o/issues/817#issuecomment-325975030

-- 
Lokesh
Freenode, OFTC: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by runcom** [comment]
This is the build tag we need to use when building for ubuntu `containers_image_ostree_stub`

**Comment by lsm5** [comment]
Just pushed a new cri-o build cri-o_1.0.0-alpha.0.2-1~ubuntu16.04.2~ppa1
for xenial to PPA that shouldn't need
libostree-1-1. Check it out.

On Wed, Aug 30, 2017 at 05:35:09AM -0700, Antonio Murdaca wrote:
> This is the build tag we need to use when building for ubuntu `containers_image_ostree_stub`
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes-incubator/cri-o/issues/817#issuecomment-325976546

-- 
Lokesh
Freenode, OFTC: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by mrunalp** [comment]
@lsm5 We should be calling it beta.0.x as that was the last cri-o release.

**Comment by lsm5** [comment]
On Wed, Aug 30, 2017 at 08:21:51AM -0700, Mrunal Patel wrote:
> @lsm5 We should be calling it beta.0.x as that was the last cri-o release. 

I've been building master branch.
I called it alpha.0 because I see this in cmd/crio/main.go

`app.Version = "1.0.0-alpha.0"`

Should that be changed to beta? Or should I be building the beta git tag
instead?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes-incubator/cri-o/issues/817#issuecomment-326025127

-- 
Lokesh
Freenode, OFTC: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by mrunalp** [comment]
We missed bumping it last time. https://github.com/kubernetes-incubator/cri-o/commit/f35147e23c13440ff7e18d04ef138596ad79401b
We could carry that.

**Comment by lsm5** [comment]
On Wed, Aug 30, 2017 at 05:01:42PM +0000, Mrunal Patel wrote:
> We missed bumping it last time. https://github.com/kubernetes-incubator/cri-o/commit/f35147e23c13440ff7e18d04ef138596ad79401b
> We could carry that. 

ack thanks, will rebuild in a bit..
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes-incubator/cri-o/issues/817#issuecomment-326054950

-- 
Lokesh
Freenode, OFTC: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by rhatdan** [comment]
I think this is fixed so closing.

**Comment by jsmickey** [comment]
Still getting the same error as originally reported.  Same output as reported by @sameo

**Comment by lsm5** [comment]
@jsmickey are you on either of xenial or zesty?

**Comment by rhatdan** [comment]
The latest cri-o should figure out whether or not libostee is supported and turn it off.  I actually think for CRI-O we should just not compile ostree in.  For kpod we need this support if it is supported since an output format of containers/image is ostree.

**Comment by lsm5** [comment]
so skopeo ends up pulling in libostree-1-1. I gotta check and change the deps to use skopeo-containers instead.

**Comment by jsmickey** [comment]
Xenial

**Comment by lsm5** [comment]
ah btw, make sure you've enabled https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak as well. I'll do new builds to change dep to skopeo-containers
